apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webpage-@color@
spec:
  replicas: 1
  template:
    metadata:
      labels:
        color: @color@
    spec:
      containers:
      - name: bgdemo
        image: 192.168.1.64:5000/bgdemo:@Ver_imagendddddasda@
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80